notifications:
  email: false
language: go
go:
- 1.11.x
install:
- curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
script:
- make test
before_deploy:
- make dist
deploy:
  provider: releases
  api_key:
    secure: Jzt2PNXn28VI9ozDt2bp6g14A/BbwP4r+EEPzb4kQ6m4ZhoacciYnsqkNvJ1Pnnemg4yFagJwdKA1Kd6GFaH1J5OvAbz2yeQJyd1mkjDkeLAJPnmA7i/6SAX/BSAo8D13m46O0cvGT8uumQ+npXoH1p9ASi7CTEMJ+Tt0vew166GCVdNbFQu0LGTJG19U/22TK0yGLfC6wJmdeV6ThFa4UocmxA/yYYDOy0QO3cDfjGjyfwyHfCOrjZg82jt+I1z0CpEkPNsOASpXnq29VsspTliw/RIiLRi9WS2RyoEmXQ2sb6ERfQNbVmd1xkHDhRz5G0WovmbHQQlrh2OycId376WzJtmxV9NKUmC36jsD3vHVgBEPgIBEiFnVK1k16wQ//cB7gOlQg6ww5EvYYhGqdHLzD0ysnWvUy7zoHjjyKBi4ow/qrRc7iEsyzuZa42Cwd7hjraV4y8PZY0TeiWZxBUUMNQ/+Aa/7ol6r4+KGFkL/kwiTBrcAi3ULU8YXB8BBEQDuSDgiWrW5B4Qup6+ZYf+kAko4HLj8g0QgrobvXOnjNrBD7Ak4WR6OnZ0Tj4Qf6CwibmqU3oQxu8hLnx0dMC6hYY4EVzIxIH41Gq73hCM8s8HMWpDGpZtKjXSzl/bxsV1r2464rRzBCOiARGPnofjWsCRwyqMXCXZPKd0OWs=
  file: dist/com.kaakaa.github.mattermostbadge-*.tar.gz
  file_glob: true
  skip_cleanup: true
  on:
    repo: kaakaa/mattermost-badge-plugin
    tags: true